### ISSUE TITLE
Foreground notifications on Android not working

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/PushNotifications#11]
Many times foreground notifications are not being received by the app, but they always are being received in the task bar. When the notification is not being received by the app, changing to another webView sometimes causes that all pending notifications are being received together. I believe that the background webViews (not visible in app) are being frozen and the code is not being executed, causing this issue.

I'm starting to suspect that there is a really big problem in crosswalk that is not processing background webViews. If i'm right, and this is a crosswalk problem, then may be that other bugs and issues reported in steroids are also being affected by this problem.

**Comment by pre** [comment]
From [forums](https://forums.appgyver.com/#!/steroids:anyone-implemented-appgyver):
>  I alwasy will get a push to my device that is never the issue, BUT but my callback will get hit 2 times when i'm in the foreground. The first one is all good and it knows that i'm in the foreground… but then I STILL see something in the system tray (have NO clue how to suppress that.) And when i press the one in the system tray it comes in as a background cold-start when i'm looking right at my app! just WAY off.. and it crashes my app… so still not working at all and I"m not sure if anyone has gotten a successful foreground flow working for Android or not. Please do let me know if you see the same thing

**Comment by fidoboy** [comment]
I think that I've solved similar problem, see here for more info:

**Comment by fidoboy** [comment]
I'm sorry, here is the link: https://github.com/AppGyver/PushNotifications/issues/8

**Comment by jeffthompson1971** [comment]
I really would like the ability to suppress anything in the system tray when in the foreground.   Is that a pull request i should open or is that in the works?

**Comment by fidoboy** [comment]
@jeff take a look at the post that I've linked, you can use my fork where this problem is solved. Test it and report your impressions and experience using it... I believe that it works fine
