### ISSUE TITLE
Metadata on iOS not available on notification object.

### ISSUE THREAD

**Issue by roberto-robles** [AppGyver/PushNotifications#12]
Right now I am switching to use this plugin, and the only missing thing for now is that there's no way for us to get metadata from that payload. Only available data is the one that is allowed on the aps.

**Comment by roberto-robles** [comment]
I guess this is addressed on #6

**Comment by fidoboy** [comment]
I think that now, with this code: https://github.com/fidoboy/PushNotifications/blob/master/src/ios/AppDelegate%2Bnotification.m it should work as expected. Now custom vars are being added into the notification message structure using the ```custom```object, so from javascript event you can access to any custom var this way: ```notification.custom.myvarname``` and standard values do work as usual in this way: ```notification.badge``` or ```notification.alert```. From my POV this code should be added also into the #next branch being developed by @harsaharsa to allow custom vars on iOS as it's working right now on Android using the payload.

**Comment by harsaharsa** [comment]
Fixed now for iOS in master branch!
