### ISSUE TITLE
How to get iOS device token for local Push Notification testing with ruby

### ISSUE THREAD

**Issue by justincolangelo** [AppGyver/PushNotifications#16]
In the documentation most of the things needed to test push notifications on iOS are there. The last bit is the device token which is not mentioned in the guide. The device token can be found in Xcode, but how do we get that information when we are using a Steroids app?

**Comment by roberto-robles** [comment]
You need to use the PushNotification object to register the device, and in the success-handler callback you will get your token.

**Comment by harsaharsa** [comment]
So viable options are

1) Send it to a server via AJAX
2) Output it via `supersonic.logger.log` to the Steroids Connect screen and copy it from there
3) Save it to localStorage or output via `console.log`, and fetch it via the Safari debugger
4) Show it visually and copy it down (e.g. via alert, a bit onerous but doable)

Closing this now!
