### ISSUE TITLE
Not receiving notifications on iOS after registration

### ISSUE THREAD

**Issue by MaksaPN** [AppGyver/PushNotifications#20]
Hello guys,

I hope this is the place where I should ask this question, if not, my apologies and could you direct me where should I ask this.

I have ran into a problem with push notifications for iOS. The logic is as simple as it gets: you register to receive notifications and then subscribe to receive foreground and background notifications. This works properly on Android but, for some reason, it does not work on iOS.

I have tried everything I could think of and left with no further ideas. First of all I have verified that my Laravel API is sending the notifications correctly with a colleague who is an  iOS developer, who created a sample app to receive notifications from our API, which he had received successfully.

I have forked the plugin's repository and changed the iOS executable code and placed (again, with assistance from a colleague who is an iOS developer) alerts everywhere to see through the process from iOS perspective. Once again, I have confirmed that iOS application registers for push notifications and starts the subscribe channel, but yet again the application was unable to receive a notification. Note: I have enabled push notifications, and the app shows up in the list on the device apps which have enabled notifications. I have also tried with your Ruby sample server and got identical results - the native application receives the notification without any issues.

Further on, I have created a sample app from scratch, just to see if I could get it to receive and eliminate possible issues with the setup in my original application. Test application also failed to receive any notifications on iOS. This is the test application Appgyver address, if that can help: https://cloud.appgyver.com/applications/50462. 

This is my code on the client side:

    function registrationHandler(deviceToken) {
        if (deviceToken != dataService.getDeviceToken()) {
            dataService.setDeviceToken(deviceToken);
        }
        window.plugins.pushNotification.onMessageInForeground(messageInForegroundHandler, errorHandler);
        window.plugins.pushNotification.onMessageInBackground(messageInBackgroundHandler, errorHandler);
    }
    function errorHandler(error) {
        alert('Error occured - ' + error);
    }
    function messageInForegroundHandler(notification) {
        var message = notification.message || notification.alert;
        console.log(message);
    }
    function messageInBackgroundHandler(notification) {
        var message = notification.message || notification.alert;
        if (notification.coldstart) {
            console.log(message);
        }
        else {
            console.log(message);
        }
    }
    document.addEventListener("deviceready", function () {
        if (device.platform == 'android' || device.platform == 'Android') {
            window.plugins.pushNotification.register(
                registrationHandler,
                errorHandler, {
                    "senderID": "<MY-APP-ID>"
                });
        }
        else if (device.platform == "ios" || device.platform == "iOS") {
            window.plugins.pushNotification.register(
                registrationHandler,
                errorHandler, {
                    "badge": "false",
                    "sound": "true",
                    "alert": "true"
                });
        }
    });

This is my code on the server side (PHP - Laravel 5):

    public function sendiOSPush($userId, $messageArray)
    {
        $deviceTokens = $this->users->find($userId)->iOsTokens()->get();
    
        $passphrase = '<MY-CERTS-PASSPHRASE>';
        $message = json_encode($messageArray, JSON_PRETTY_PRINT);
        
        foreach($deviceTokens as $deviceToken)
        {
            $ctx = stream_context_create();
            stream_context_set_option($ctx, 'ssl', 'local_cert', public_path().'/ck.pem');
            stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);
        
            $fp = stream_socket_client(
                'ssl://gateway.sandbox.push.apple.com:2195', $err,
                $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

            if (!$fp)
                exit("Failed to connect!" . PHP_EOL);

            $body['aps'] = array
            (
                'alert' => $messageArray["subtitle"],
                'sound' => 'default'
            );
            
            $body['payload'] = json_encode($messageArray["payload"], JSON_PRETTY_PRINT);
            $body['type'] = $messageArray["type"];

            $payload = json_encode($body);
            $msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken->token) . pack('n', strlen($payload)) . $payload;
            $result = fwrite($fp, $msg, strlen($msg));
            fclose($fp);
        }
        
        return true;
    }

Thank you in advance for your help.

**Comment by djjolicoeur** [comment]
I had some issues around iOS that sound similar to what you are seeing when I was setting up our APNS.  Push notifications are being sent but never received by the device.  No errors.  Apple is very particular about the certificate and your .mobileprovision matching.  I see you are targeting the sandbox, are you using a development .mobileprovision file in your build and a development APNS cert from apple created with the same Application ID? Both of these have to be set up correctly or you will not get the push notifications on the device via sandbox.  The same applies to production....both have to be production and created with the same Application ID in apples provisioning center or else APNS will not forward the notification to the device, but at least in my experience, you will not get any errors either.

**Comment by MaksaPN** [comment]
Yes, I have triple-checked all of the steps with the certificates, and I've done everything according to manual. Also, the same configuration works fine on test iOS app, literally using the same code that this plugin uses. I'm baffled with this...

**Comment by harsaharsa** [comment]
If you are using the correct provisioning profiles, the correct device token and correct APNS gateway, the plugin code doesn't even affect if the push is received or not (compare to Android, where you have to construct the notification center notification manually when the push message comes in).

Thus, to ensure that everything is in order in the app package and your server, it's best to not have the app running – if it's set up correctly, the push message will appear in the notification center. You can then move on to ensure that the push message is handled correclty in your app.

I really can't think of a way to help other than "doublecheck everything" – it works consistently on all our test devices here. :( Are you sure the device token you're using is the one given by the push plugin's register command?

**Comment by MaksaPN** [comment]
Yes, it uses the correct device token which is extracted and then posted to server and saved to a database. I use this token (as well as android registrationIds) to later push notifications from server. I have tried what you're saying about not having the application run and checking with notification center, but had no results. I have placed js alerts after each step and I can see that it returns device token and registered for both foreground and background notifications. I've used the same code provided in the walkthrough to set up a test appgyver project, and the result is the same - android working without a glitch and iOS still not receiving any notifications.
I also thought of the certificates as the problem, but the application builds without issues and the same certificates are used in a test native app (created with same package name) which receives the notifications sent by api to apns without any issues. Am I missing something here in the process?
I have tested this on the latest iOS 8.2, could this be a problem? Is there a way to build the application locally and debug via Xcode to try to catch the issue?

**Comment by fidoboy** [comment]
I can also confirm, if it helps that the plugin works fine on iOS devices. The message appears in the notification center and also is triggering the javascript listener when the app is foreground. So if it is failing it could be due to:

1. Bad javascript handling

2. Bad formatting in the message sent by the server

**Comment by MaksaPN** [comment]
@fidoboy
1. What do you mean by bad handling, I have used exactly the same code as provided in the example?
2. The native app receives the notification correctly which means it is sent correctly, so I dismissed this as issue in the start.

**Comment by fidoboy** [comment]
There is also a third option that is that the certificates are wrong. You should use a production certificate if you test with Appgyver adhoc or scanner build and a development certificate if you use a debug scanner build.

**Comment by MaksaPN** [comment]
@fidoboy
Yes, the production certificate is used and like I said, using the built certificates I've build the native iOS app and received the push notifications without any issues.

**Comment by fidoboy** [comment]
Bad handling wants to mean that may be you aren't using the exact same code provided in the example. As @harsaharsa suggested, it could be useful if you test first if the notitication appears in the notification center while your app is closed or in background. This way you will know if the server side and certificates are ok.

**Comment by MaksaPN** [comment]
Tried with the application being inactive and closed.

**Comment by fidoboy** [comment]
It shouldn't be related to your problem, but looking your code i've noticed that you are using window.plugins.pushNotification.register twice for Android and iOS with different setups. You can use it only once and merge both configurations into the same call, it works fine that way also (i'm doing that way). senderID is ignored if the target device is iOS.

**Comment by fidoboy** [comment]
If your notification doesn't arrives to notification center then this means that your device is not registered or your server setup is wrong (php code)

**Comment by MaksaPN** [comment]
Thank you for all of your guys' feedback, I will try again the entire process and let you know the results.

**Comment by fidoboy** [comment]
Good luck @MaksaPN ! And remember that plugin works fine so double check your code and each step in the process. Try to simplify to discard failures. You can also use steroids.logger.log and monitor in your browser page the values. Put one of them in messageInForegroundHandler before anything else to get the notification object value. If the message doesn't works in your notification center then your javascript is useless and the problem is before that; either in your server PHP or with the registration process

**Comment by djjolicoeur** [comment]
"Yes, the production certificate is used and like I said, using the built certificates I've build the native iOS app and received the push notifications without any issues."

if you are using production certificates, and you are using the exact code you published above, you will not get any notifications.  you are pointed at the sandbox APNS environment:

```
$fp = stream_socket_client(
            'ssl://gateway.sandbox.push.apple.com:2195', $err,
            $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);
```

 which will only work with dev certificates.  try pointing at the production APNS service.  

hope this helps.

**Comment by MaksaPN** [comment]
I've manage to resolve this by regenerating development provisioning files using different apple credentials, and as we all suspected, turns out that that was the issue (both code bases are working properly now without any changes). I'm closing this issue now, because it was a configuration problem rather then issue of the platform. Once again, guys, thank you all for all of your help and directions.
