### ISSUE TITLE
Can we ask for push permissions more than once?

### ISSUE THREAD

**Issue by benjamincharity** [AppGyver/PushNotifications#22]
For some applications, push notifications are necessary for proper use. Obviously we cannot force them if disabled; but is there a way to re-ask for permissions if we don't have permissions but deem them mission critical for an app?

Currently it seems that if push was disabled by the user I simply see the `Push notifications are not enabled for this app` error which could also mean the registration didn't work correctly. 

Our registration flow asks for push permissions and geolocation permissions at specific points with associated messaging. I'm not sure how to actually test this flow since the register function never asks the user after that first time. (meaning I can't reset and go through the flow again)

Any insight on how others have been handling this would be greatly appreciated.

[Side note: It would also be nice to know what is or is not enabled.. badge but not shown on lock screen etc]

**Comment by harsaharsa** [comment]
On iOS, that's not possible – you need to instead show a dialogue that instructs the user to go to Settings app and enable the push notifications.

As for the data about what's enabled or not, that's not available via the error message:

https://github.com/AppGyver/PushNotifications/blob/master/src/ios/AppDelegate%2Bnotification.m#L67-L71 is triggered, but the NSError is not used in the plugin result:
https://github.com/AppGyver/PushNotifications/blob/master/src/ios/NotificationService.m#L47-L61

**Comment by benjamincharity** [comment]
Thanks for the info @harsaharsa. A dialogue message does sound like the best way to go.

**Comment by benjamincharity** [comment]
One more question @harsaharsa, since we cannot force iOS to ask the user again about permissions, is there a specific way to re-test that initial permissions flow? Do I need to create new certificates with a new app name to make iOS believe that it is a brand new app? Or is there a way to delete the app from my test device and reset it so that iOS 'forgets' all associated preferences? (Currently it seems to save the preferences even when deleting the app from my test device)

Thanks again!

**Comment by harsaharsa** [comment]
@benjamincharity see https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG42 for instructions

**Comment by benjamincharity** [comment]
Ahh you're a lifesaver! Thanks for pointing a first-timer in the right direction!
