### ISSUE TITLE
Does not work from background webView

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/PushNotifications#3]
I've created my event listener in a initial webView (preloaded from start) where i register the device and create the event listener for foreground and background messages. In my initial tests, this does not work on iOS and neither on Android. The device is being registered fine...

**Comment by fidoboy** [comment]
any news about this issue? can not use it on iOS or android...

**Comment by fidoboy** [comment]
can't get it working....

**Comment by pre** [comment]
Could you share a code example?

Are you experiencing this issue with [new messages with identical payload being discarded](https://github.com/AppGyver/PushNotifications/issues/5)?

**Comment by fidoboy** [comment]
Well, the behavior seems to be a bit inconsistent ATM. On Android, it works (however i'll do more tests) but when the app is on foreground, the notification is being received twice, in my app and at the same time the notification appears on system notifications panel (the same than when the app is in background mode or closed). I can also hear the system sound even when my app is foreground and i don't want to have that system sound. 

On iOS, in my tests, it only works in background mode, it displays the badge and also the sound, but when the app is in foreground nothing happens...

If you can confirm that this works fine on your tests, i'll try to re check my code again to be sure, but i believe that it's all ok and if it works on Android, it does not have sense that it fails on iOS using the same code...

**Comment by pre** [comment]
There is an inconsistency with iOS and Android at the moment. Subsequent notifications are received by the foreground listener on Android but discarded on iOS: #5

**Comment by fidoboy** [comment]
I've just created a build using latest version of this plugin on iOS. Push notifications when app is in foreground state doesn't work; the notification never arrives. It works fine in background mode. With android, the behavior is very erratic and sometimes the notification arrives when app is in foreground, but other times it doesn't .

**Comment by fidoboy** [comment]
I should add that I've tested it with a complex MPA where all notification management is done from a single background webView where I've put the event listeners...

**Comment by fidoboy** [comment]
It's not subsequent notifications, there is no notification received when in foreground on iOS; they simply doesn't work...

**Comment by pre** [comment]
We have now changed the implementation so that messages contain a uuid and timestamp. That will allow subsequent push messages with identical payload be treated as individual messages (previously they were discarded if the payload was identical).

Please rebuild your application with the newest changes.

Does this resolve your issue?

**Comment by fidoboy** [comment]
No, it doesn't solve it. If you see my post date/time you will notice that i've posted it after newest changes. PushNotifications doesn't work on iOS neither Android right now

**Comment by pre** [comment]
Could you please post a code reproduction how I could check that it does not work? 

I'm having hard time figuring out what is the issue you're having. For us the plugin is working as expected.

**Comment by pre** [comment]
2) Are you using `supersonic.push()` or the plugin api directly?

**Comment by fidoboy** [comment]
I'm not using supersonic but steroids.

**Comment by fidoboy** [comment]
My code:

```
function registrationHandler(deviceToken) {
	pushNotification.onMessageInForeground(messageInForegroundHandler, errorHandler);
	pushNotification.onMessageInBackground(messageInBackgroundHandler, errorHandler);
        .........         
}
function messageInForegroundHandler (notification) {
       ..........
}
function onDeviceReady() {
	document.removeEventListener("deviceready", onDeviceReady, false);
        pushNotification = window.plugins.pushNotification;
	if (pushNotification) pushNotification.register(registrationHandler, errorHandler, {
		"badge":"true",
		"sound":"true",
		"alert":"true"
	});
}
document.addEventListener("deviceready", onDeviceReady,false);

```

**Comment by fidoboy** [comment]
steroids.logger.log doesn't work, so doing my tests is much more difficult; having steroids.logger.log could help a lot... Anyway, by knowing that plugin works for you, i'm doing my tests again...

**Comment by fidoboy** [comment]
Ok, i've found a problem on iOS build. The `messageInForegroundHandler` works but notification parameter doesn't have all my custom properties (i'm using two and it was working fine with other push plugins before)

**Comment by fidoboy** [comment]
So, basically my problem (and there is a bug on this plugin) is that notification object doesn't have all properties and it's filtering the custom properties that my server is sending...

**Comment by fidoboy** [comment]
On Android, `messageInForegroundHandler` function is not being triggered

**Comment by fidoboy** [comment]
notification object, on iOS, has sound, alert, timestamp, timestamp, uuid and foreground, but it's missing my other properties that the server is sending; Android is receiving them on the notification.payload

**Comment by fidoboy** [comment]
I think that the problem is on this line:

```NSMutableDictionary* notification = [NSMutableDictionary dictionaryWithDictionary:[userInfo objectForKey:@"aps"]];```

on AppDelegate+notification.m. The notification object is not getting all `userInfo` contents

**Comment by fidoboy** [comment]
Look here: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html at bottom, examples of JSON Payloads, example 5. There is other values outside `aps` and this plugin is only getting the aps contents, discarding other values...

**Comment by fidoboy** [comment]
after my proposed change, sound, badge and alert should be accessed with `notification.aps.alert` and not using `notification.alert` Other alternative, to keep current code working, could be to move the custom properties inside other nested object, called `custom` for example; this way, you could keep `notification.alert` and then get `notification.custom.acme-account` to get a custom value (acme-account in this example)

**Comment by fidoboy** [comment]
Ok, for me, issue is solved on iOS, but still doesn't work on Android...

**Comment by fidoboy** [comment]
Ok, finally i've solved the problem. It was on my side, my code was buggy, so i'm sorry for the false warning. Anyway, it was very hard to locate it cause i was working blind due to steroids.logger.log is not working since long time ago. So issue closed :)

**Comment by harsaharsa** [comment]
Great!
