### ISSUE TITLE
error: Class not found 

### ISSUE THREAD

**Issue by agilastic** [AppGyver/PushNotifications#4]
Hi,
first of all thanks for you great work.  
With the sample code I get the following error message  on Android "error: Class not found", when running pushNotification.register it breaks and goes to the errorHandler :-(

Googeling around it seems to be a popular problem. But I'm stuck to fix this issue. 
My settings:
- AppGyver Steroids² 4.0.4
-Andorid 4.2
- real device

Somebody of you who had similar problems and could solve it?

THX in advance!

**Comment by pre** [comment]
Did you build your AppGyver Scanner from the [Build Service](https://cloud.appgyver.com)? The Scanner downloaded from Google Play does not include this plugin by default.

**Comment by harsaharsa** [comment]
Closing until futher comments.
