### ISSUE TITLE
Messages with identical content are silently discarded

### ISSUE THREAD

**Issue by pre** [AppGyver/PushNotifications#5]
In Android there is another scenario when the notification is tapped, the same notification is delivered to the application twice. As a fix, currently the new push messages with identical payload are silently discarded by the native side on iOS, but NOT discarded on Android.

This is confusing.

Add a timestamp and/or unique identifier to the message payload so that only "real" duplicate messages would be discarded.

**Comment by harsaharsa** [comment]
This is now fixed.
